### PR TITLE
dfx.json: Don’t say “mainnet”, say “mercury”

### PR DESCRIPTION
**Pull request by nomeata**
as it seems to be the “more proper” name.

### CODE REVIEW

**Comment by jplevyak** [comment]
We agreed to call this mainnet.

**Comment by jplevyak** [comment]
@samuelburri was involved in that naming discussion

**Comment by samuelburri** [comment]
@nomeata @jplevyak the term `mainnet` was agreed with Brendan and Eric. Background, Eric expects that one day we might have other 'nets', e.g. in China.

**Comment by nomeata** [comment]
Thanks for the clarification!

**Pull request closed without merging**
