### PR TITLE
Don't deploy Release Candidate

### PR DESCRIPTION
**Pull request by nmattia**
Internet Identity used to have a weekly release schedule. This is not the case anymore, so this removes release candidates, automated RC deploys and RC notifications.

### CODE REVIEW

**Review by frederikrothenberger — COMMENTED** [review]
What about just removing the schedule? I think manually dispatching release candidate deployment is useful.

**Comment by nmattia** [comment]
I think this workflow will just rot then. We could still run the workflow e.g. daily to ensure it works, and just remove the slack message. WDYT?

**Comment by frederikrothenberger** [comment]
> I think this workflow will just rot then. We could still run the workflow e.g. daily to ensure it works, and just remove the slack message. WDYT?

Yeah, that's good too. 👍

**Comment by nmattia** [comment]
@frederikrothenberger actually, we still deploy to fgte on every commit on the `main` branch, I think we can just remove this workflow here

**Review by frederikrothenberger — APPROVED** [review]

**Comment by nmattia** [comment]
Ok not 100% sure what to do here; I'll revisit this in a bit

**Pull request closed without merging**
