### PR TITLE
Migrate simple pages to Astro pages

### PR DESCRIPTION
**Pull request by lmuntaner**
Continue with the migration to use Astro pages instead of dynamic pages with [page].astro

In this PR, I only moved the simple pages that have no dependencies.

<hr/><details><summary>🟡 Some screens were changed</summary></details>

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* **#2314** <a href="https://app.graphite.dev/github/pr/dfinity/internet-identity/2314?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/internet-identity/2314?utm_source=stack-comment).

**Review by nmattia — APPROVED** [review]
Thanks!

Just a thought: as I was moving those components I started replacing the various `console.log`s on action with toast messages, which are friendlier when clicking around in the showcase. Might be worth doing here as well.

**Comment by lmuntaner** [comment]
> Thanks!
> 
> Just a thought: as I was moving those components I started replacing the various `console.log`s on action with toast messages, which are friendlier when clicking around in the showcase. Might be worth doing here as well.

Done!

I was wondering whether there was a reason some were toasts and others console.logs

**Comment by nmattia** [comment]
> I was wondering whether there was a reason some were toasts and others console.logs

Basically started with console.logs before we had toasts, but incrementally changed for toasts because they give visual feedback that something was clicked

**Pull request merged**
