### PR TITLE
Update automatic release notes to make commit and sha256 more visible

### PR DESCRIPTION
**Pull request by nmattia**
As title says; this also adds a README for the release action which explains how to run the action locally (and tweaks the action to be able to run outside GHA).
 
Here's what [release-2022-03-30](https://github.com/dfinity/internet-identity/releases/tag/release-2022-03-30) would have looked like (some links and shas are just placeholders):

---

This is release [release-2022-03-30](https://github.com/dfinity/internet-identity/releases/tag/release-2022-03-30) for commit [f56e1430cdd31ed21e96575d3fba05a7a1369191](https://github.com/dfinity/internet-identity/commit/f56e1430cdd31ed21e96575d3fba05a7a1369191).
The sha256 of production asset [internet_identity_production.wasm](https://github.com/dfinity/internet-identity/releases/download/release-2022-03-30/internet_identity_production.wasm) is [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855](https://example.com#step:step:1).

## What's Changed
* Fix typo in README by @nmattia in https://github.com/dfinity/internet-identity/pull/579
* New alias screenshot: wait for loader to go by @nmattia in https://github.com/dfinity/internet-identity/pull/584
* Remove old screenshots before downloading new ones by @nmattia in https://github.com/dfinity/internet-identity/pull/581
* Update features and flavors documentation by @nmattia in https://github.com/dfinity/internet-identity/pull/580
* Fix screenshot upload by @nmattia in https://github.com/dfinity/internet-identity/pull/586
* Clarify build flavors section of release by @nmattia in https://github.com/dfinity/internet-identity/pull/582
* Make better use of space in README table by @nmattia in https://github.com/dfinity/internet-identity/pull/585
* Add examples on how to use dev build by @nmattia in https://github.com/dfinity/internet-identity/pull/587
* Update README by @nmattia in https://github.com/dfinity/internet-identity/pull/590
* Add usage and --help to docker-build by @nmattia in https://github.com/dfinity/internet-identity/pull/589
* Add 'Getting Help' section to README by @nmattia in https://github.com/dfinity/internet-identity/pull/591
* Fix link to Integration section by @nmattia in https://github.com/dfinity/internet-identity/pull/592
* Run 'npm audit fix' by @nmattia in https://github.com/dfinity/internet-identity/pull/594
* Bump node-forge from 1.2.1 to 1.3.0 in /demos/sample-javascript by @dependabot in https://github.com/dfinity/internet-identity/pull/600
* Bump node-forge from 1.2.1 to 1.3.0 in /demos/testnet_app by @dependabot in https://github.com/dfinity/internet-identity/pull/599
* Bump minimist from 1.2.5 to 1.2.6 in /demos/sample-javascript by @dependabot in https://github.com/dfinity/internet-identity/pull/598
* Bump minimist from 1.2.5 to 1.2.6 in /demos/testnet_app by @dependabot in https://github.com/dfinity/internet-identity/pull/596
* Bump minimist from 1.2.5 to 1.2.6 in /demos/using-dev-build by @dependabot in https://github.com/dfinity/internet-identity/pull/597
* Clean up HACKING.md, CONTRIBUTING.md by @nmattia in https://github.com/dfinity/internet-identity/pull/601
* Add link to discord channel by @nmattia in https://github.com/dfinity/internet-identity/pull/602
* Fix with-selenium-standalone by @nmattia in https://github.com/dfinity/internet-identity/pull/603
* Use invite link for Discord by @nmattia in https://github.com/dfinity/internet-identity/pull/605
* Don't allow adding too many devices by @nmattia in https://github.com/dfinity/internet-identity/pull/595
* Fix hasRecoveryDevice by @nmattia in https://github.com/dfinity/internet-identity/pull/604
* feat: 100% on chain logo and spacing by @peterpeterparker in https://github.com/dfinity/internet-identity/pull/607
* Generate custom release notes by @nmattia in https://github.com/dfinity/internet-identity/pull/608

**Full Changelog**: https://github.com/dfinity/internet-identity/compare/release-2022-03-15...release-2022-03-30

## Build flavors

For more information please see the [Build flavors](https://github.com/dfinity/internet-identity/tree/release-2022-03-30#build-features-and-flavors) section of the README.

| Filename | sha256 | Verify |
| --- | --- | --- |
|[internet_identity_production.wasm](https://github.com/dfinity/internet-identity/releases/download/release-2022-03-30/internet_identity_production.wasm)|`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`|[CI Run](https://example.com#step:step:1)|
|[internet_identity_dev.wasm](https://github.com/dfinity/internet-identity/releases/download/release-2022-03-30/internet_identity_dev.wasm)|`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`|[CI Run](https://example.com#step:step:1)|
|[internet_identity_test.wasm](https://github.com/dfinity/internet-identity/releases/download/release-2022-03-30/internet_identity_test.wasm)|`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`|[CI Run](https://example.com#step:step:1)|

### CODE REVIEW

**Comment by dubovitskaya** [comment]
Thanks a lot Nicolas! Looks great! A couple of suggestions:

1. It would be nice to specify major changes for an upgrade before providing a full list of commits (since it is hard to digest).
2. (minor) In the table with the release files they are sorted by the name, but I would specify the prod one first...

WDYT?

**Comment by nmattia** [comment]
@dubovitskaya thanks, very good points! 

> It would be nice to specify major changes for an upgrade before providing a full list of commits (since it is hard to digest).

Unfortunately figuring out which changes are major from the release script is not straightforward. The good news is that we can always edit the release notes; for [release-2022-03-30](https://github.com/dfinity/internet-identity/releases/tag/release-2022-03-30) for instance we highlighted a few changes and PRs in the intro.

> (minor) In the table with the release files they are sorted by the name, but I would specify the prod one first...

I've changed the order of the release assets to have prod, then dev, and finally test. I've edited the PR description to include the updated layout.

**Review by dubovitskaya — APPROVED** [review]
Thanks a lot!

**Review by frederikrothenberger — APPROVED** [review]
Thanks!

**Pull request merged**
