### PR TITLE
Update authentication mobile styles

### PR DESCRIPTION
**Pull request by mstrasinskis**
# Motivation

Update authentication page styles to display more info on mobile

# Screenshots

## pixel
localhost_8080_(Pixel 5)
---
## samsung S8+
localhost_8080_(Samsung Galaxy S8+)
---
## Iphone 12 pro
localhost_8080_(iPhone 12 Pro)
---
## Iphone SE
localhost_8080_(iPhone SE)
---

### CODE REVIEW

**Comment by frederikrothenberger** [comment]
I just did a demo deployment of your PR here:
• Demo App: https://6zm7l-dyaaa-aaaaa-qaaka-cai.identity.dfinity.network/
• II: https://6cjdo-zaaaa-aaaaa-qaaiq-cai.identity.dfinity.network/

**Comment by frederikrothenberger** [comment]
Updated the deployment

**Review by frederikrothenberger — COMMENTED** [review]
Unfortunately, now the padding seems off in desktop view. See changes to `screenshots/25-authenticate-unknown-anchor-desktop.png` and `screenshots/24-authenticate-known-anchor-desktop.png`

**Comment by mstrasinskis** [comment]
> Unfortunately, now the padding seems off in desktop view. See changes to screenshots/25-authenticate-unknown-anchor-desktop.png and screenshots/24-authenticate-known-anchor-desktop.png
Fixed

**Comment by frederikrothenberger** [comment]
Updated the demo deployment again.

**Comment by nmattia** [comment]
> Update authentication page styles to display more info on mobile

And add a new logo, correct?

**Comment by nmattia** [comment]
In the first iteration we made sure that the space for the extra button was already present to avoid things jumping around. Was the behavior changed on purpose?

https://user-images.githubusercontent.com/6930756/173335730-0499a328-d738-4cd6-83e2-fd05d882f436.mov

**Comment by frederikrothenberger** [comment]
> In the first iteration we made sure that the space for the extra button was already present to avoid things jumping around. Was the behavior changed on purpose?

It was definitely intentional for the error message.

Imho, if everything still fits on a single screen when keeping the space for the `register` button, we should revert to reserving the space there again.

**Review by frederikrothenberger — APPROVED** [review]

**Comment by nmattia** [comment]
> if everything still fits on a single screen when keeping the space for the register button, we should revert to reserving the space there again.

So I'm guessing it didn't fit?

**Pull request merged**
