### PR TITLE
Fix selenium test upon removing last device

### PR DESCRIPTION
**Pull request by gobengo**
I noticed this part of the selenium tests were failing when for my other README changes, so tried to fix it.

## Description

I think the tests had not been updated upon https://github.com/dfinity/internet-identity/pull/297

The old test asserted that you could remove the last device after an alert, and then would be sent back to the Welcome screen.
Now it asserts you can't, and you stay on the same page with the device *not* removed.

## Motivation and Context

* moving towards green tests
* notably, there's still a selenium test that fails

## How Has This Been Tested?
* github ci + selenium

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] test fix

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by gobengo** [comment]
Timeboxed this but couldn't get it fixed. :/

**Comment by gobengo** [comment]
Searched web as last resort, and looks like this 'back to back alert' case is quirky for others too https://stackoverflow.com/questions/48082926/how-to-handle-back-to-back-alerts-on-selenium-webdriver-automation

**Comment by gobengo** [comment]
I fixed one test but another still fails (and was there before). I think this is an improvement regardless.

**Review by ggreif — APPROVED** [review]
Thanks for doing this, it was quite distracting  to me when doing #298.

LGTM!

I looked at https://github.com/dfinity/internet-identity/pull/304/checks?check_run_id=2688005907#step:12:408 and it seems to appear in the context of a different flow.

**Pull request merged**
