### PR TITLE
Manage and improve VC flow edge cases and fix relying party and issuer card

### PR DESCRIPTION
**Pull request by lmuntaner**
The main motivation is to have the edge cases of the VC flow more under control.

In this PR:
* Changed on showcase page and added two more to control how the page should look like in different edge cases.
* Changed the error page title requested by product. More copy changes might come in this page, but I'm waiting for confirmation.

<hr/><details><summary>🟢 Some screens were added</summary></details><details><summary>🟡 Some screens were changed</summary></details><details><summary>🔴 Some screens were removed</summary></details>

### CODE REVIEW

**Review by frederikrothenberger — APPROVED** [review]
LGTM, thanks!

**Comment by lmuntaner** [comment]
@frederikrothenberger I switched the relying party and issuer in a new commit here.

**Comment by frederikrothenberger** [comment]
> @frederikrothenberger I switched the relying party and issuer in a new commit here.
> 
> I thought it made sense to reuse the PR because it will mean changes in the same screenshots.
> 
> But I would have been happy to do it in a new PR as well. What do you think makes more sense?

Generally, I feel changes to the screenshots should not be an argument to not split PRs. But given this is small enough, I don't mind being one. Maybe adjust the title though to reflect that you switched the relying party and issuer / it contains fixes too.

**Review by frederikrothenberger — APPROVED** [review]
LGTM, thanks.

**Comment by lmuntaner** [comment]
> > @frederikrothenberger I switched the relying party and issuer in a new commit here.
> > I thought it made sense to reuse the PR because it will mean changes in the same screenshots.
> > But I would have been happy to do it in a new PR as well. What do you think makes more sense?
> 
> Generally, I feel changes to the screenshots should not be an argument to not split PRs. But given this is small enough, I don't mind being one. Maybe adjust the title though to reflect that you switched the relying party and issuer / it contains fixes too.

Noted, I wasn't sure what you would prefer. I also prefer small PRs, that's why I put the fixes of e2e in another PR.

**Pull request merged**
