### PR TITLE
New title "Choose Identity" when logging in

### PR DESCRIPTION
**Pull request by lmuntaner**
Main motivation is to simplify the copy in certains screens as requested in https://dfinity.atlassian.net/browse/GIX-2526

<hr/><details><summary>🟡 Some screens were changed</summary></details>

### CODE REVIEW

**Comment by lmuntaner** [comment]
Changed screens:

Screenshot 2024-05-31 at 07 46 19
Screenshot 2024-05-31 at 07 47 34
Screenshot 2024-05-31 at 07 50 04
Screenshot 2024-05-31 at 07 50 12

Not changed screens where "Internet Identity" is not a title.

Screenshot 2024-05-31 at 07 49 44
Screenshot 2024-05-31 at 07 51 26

**Comment by lmuntaner** [comment]
@frederikrothenberger please review.

I noticed an inconsistency on the input backgrounds. I'll discuss it with Artem to be done later.

**Comment by lmuntaner** [comment]
@frederikrothenberger please review

**Review by frederikrothenberger — APPROVED** [review]
Do we really want to use the 🔑 emoji?
(Sorry, I'm out of the loop regarding that decision).

**Comment by lmuntaner** [comment]
> Do we really want to use the 🔑 emoji? (Sorry, I'm out of the loop regarding that decision).

Yes, that was a specific request.

**Pull request merged**
