### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by dprats**
## Description
Modified the docs to make it easy for people to know how to recover identity from a seed phrasee

## How Has This Been Tested?
I previewed it in VS code.

## Types of changes
Doc change

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nomeata** [comment]
It seems that you are committing manually created screenshots. This is of course the state of art in many projects, but I think we can do a little better: During CI, we actually take screenshots of most workflows mechanically! (see `/screenshots/`). Can we maybe use them in the docs (e.g. via a symlink)? This way they’d always be up to date, even as we change styling or wording (which is pretty neat).

**Comment by nomeata** [comment]
Sure, and no need to block merging this now, and improve later.

**Comment by nmattia** [comment]
This is looking good, merging!

**Review by nmattia — APPROVED** [review]
LGTM

**Pull request merged**
