### PR TITLE
Replace Logo

### PR DESCRIPTION
**Pull request by meodai**
On @artkorotkikh-dfinity's request, I replaced the Logo.

To make sure it is still accessible to people using a screenreader, Ive added a `<title>` to the group containing the text inside the SVG.

Screenshot 2024-06-06 at 13 44 57

<hr/><details><summary>🟡 Some screens were changed</summary></details>

### CODE REVIEW

**Comment by peterpeterparker** [comment]
> To make sure it is still accessible to people using a screenreader, Ive added a <title> to the group containing the text inside the SVG.

For a11y reason, shouldn't the `title` be more descriptive then? 

Instead of `<title>Internet Identity</title>` something like `<title>The Internet Identity logo</title>` or something?

Don't want to hijack the review just, randomly noticed the PR.

**Comment by meodai** [comment]
@peterpeterparker in this case it does not act as an alt text but as a replacement for what was the h1 before. So I wanted it to read out as it was before "internet identity".

**Comment by peterpeterparker** [comment]
Gotcha!

**Review by frederikrothenberger — APPROVED** [review]
Looks good, thanks a lot!

**Pull request merged**
