### PR TITLE
Move showcase home

### PR DESCRIPTION
**Pull request by lmuntaner**
Move the following pages to Astro:
* Showcase home
* 404
* Styleguide component

Remove the following files:
* showcase.ts
* styleguide.ts

<hr/><details><summary>🟢 Some screens were added</summary></details><details><summary>🟡 Some screens were changed</summary></details>

### CODE REVIEW

**Comment by lmuntaner** [comment]
* **#2343** <a href="https://app.graphite.dev/github/pr/dfinity/internet-identity/2343?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lmuntaner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by nmattia — APPROVED** [review]
Rubber stamp!

Do you know why some screenshots appeared? In the future please do add a description with brief overview of the changes and anything specific like why the screenshots changed!

**Comment by lmuntaner** [comment]
> Rubber stamp!
> 
> Do you know why some screenshots appeared? In the future please do add a description with brief overview of the changes and anything specific like why the screenshots changed!

Sorry, I have to get used to checking the screenshots. I don't understand why there are new screenshots. I didn't add any new pages. Unless it was because I fixed something that I didn't know was broken...

**Comment by lmuntaner** [comment]
> AFAICT you're listing all astro files, including the showcase and the flow indexes, which explains why those two now show up in the screenshots. I think you can limit the search to the stuff inside `components/`!

I only added on file inside `components` which is the `Styleguide` which doesn't appear there. I'll investigate before merging. Thanks for the pointer!

**Comment by lmuntaner** [comment]
> 
> From a superficial look it might be this:
> 
> ```ts
> const files = readdirSync("./src/showcase/src/pages/");
> const fileNames = files.map((file) => file.replace(".astro", ""));
> ```
> 
> AFAICT you're listing all astro files, including the showcase and the flow indexes, which explains why those two now show up in the screenshots. I think you can limit the search to the stuff inside `components/`!

You're right. The "flows.astro" and "components/index.astro" were not present before in the showcase. I realized the flow is duplicated, therefore I moved `flows.astro` to `flows/index.astro`. I believe that makes it more consistent, like we have for `components/index.astro`.

**Pull request merged**
