### PR TITLE
Add cargo fmt to CI

### PR DESCRIPTION
**Pull request by frederikrothenberger**
Refactor workflows to no longer duplicate rust installation and add cargo fmt to CI pipeline.

### CODE REVIEW

**Review by nmattia — APPROVED** [review]
LGTM!

**Review by nmattia — COMMENTED** [review]
What happened to having everything in one file?

**Comment by frederikrothenberger** [comment]
> What happened to having everything in one file?

I felt, that having it in backend-tests is not really fitting. So I moved it. If one file is preferred, I'd rather add it to the cargo-tests one (as it is a cargo command as well).

**Review by nmattia — COMMENTED** [review]
My 2cts: let's move it to `cargo-tests.yml` as a separate job (`cargo-fmt`) which only runs on e.g. ubuntul-latest. WDYT?

**Comment by frederikrothenberger** [comment]
> My 2cts: let's move it to `cargo-tests.yml` as a separate job (`cargo-fmt`) which only runs on e.g. ubuntul-latest. WDYT?

Agreed. I also refactored the rust installation to not duplicate the rust install commands. I hope this is ok.

**Review by nmattia — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
