### PR TITLE
chore: update links

### PR DESCRIPTION
**Pull request by dfx-json**
In preparation for the upcoming docs changes, this PR updates links that will change to reflect the new developer docs structure.

### CODE REVIEW

**Comment by nmattia** [comment]
Hi, when will the new links be effective, and will there be 301 redirects from the old links? i.e. when should this go live?

**Comment by dfx-json** [comment]
> Hi, when will the new links be effective, and will there be 301 redirects from the old links? i.e. when should this go live?
Hi @nmattia - theres a PR open currently for the docs revamp here: https://github.com/dfinity/portal/pull/1030

I plan to merge all of the submodules changes, then pull those changes into the portal repo and merge the PR. This should take place within the week.

There are redirects for the old routes, see https://github.com/dfinity/portal/pull/1030/files#diff-52b0e180f111a2b17721aa3cd7d1abc9ef35b5e922e444ea8e2145f331c6774c

**Comment by nmattia** [comment]
hi @dfx-json, I'm still a little confused. Should we go ahead and merge this then?

(note: looks like a merge/rebase went wrong here)

**Comment by nmattia** [comment]
@dfx-json I'm gonna go ahead and close this but let us know if this is still relevant!

**Pull request closed without merging**
