### PR TITLE
Add logo on top and remove spacing

### PR DESCRIPTION
**Pull request by frederikrothenberger**
Optimize authenticate authorization screen for mobile.

Deployed here for testing: https://6zm7l-dyaaa-aaaaa-qaaka-cai.identity.dfinity.network/

### CODE REVIEW

**Review by peterpeterparker — APPROVED** [review]
Rubber stamp, thanks

**Review by mstrasinskis — APPROVED** [review]
LGTM

**Review by Dfinity-Bjoern — APPROVED** [review]
Thanks!

**Review by nmattia — APPROVED** [review]
Logo is HUGE but LGTM nonetheless :)

**Pull request merged**
