### PR TITLE
Migrate showcase to static pages

### PR DESCRIPTION
**Pull request by lmuntaner**
Final motivation is to create a separate package for the showcase.

In this PR, I keep migrating some of the dynamic pages from `[page].astro` to static pages.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Current dependencies on/for this PR:
* **#2322** <a href="https://app.graphite.dev/github/pr/dfinity/internet-identity/2322?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dfinity/internet-identity/2322?utm_source=stack-comment).

**Review by nmattia — COMMENTED** [review]
Thanks! Can you remove the corresponding pages from the original showcase (`showcase.ts`) as well?

**Comment by lmuntaner** [comment]
Not yet, otherwise they are not shown in the list of showcases.

I will do that in another PR when I finish the migration.

**Review by nmattia — APPROVED** [review]
Thank you!

**Pull request merged**
